### PR TITLE
Fixed a crash when CreativeCore is not installed

### PR DESCRIPTION
**Pull request by whitebear60**
Now Forge will tell the user to install CreativeCore (instead of crashing Minecraft)

### CODE REVIEW

**Comment by CreativeMD** [comment]
Unfortunately this won't fix the issue. It will still crash.

**Comment by whitebear60** [comment]
My changes tells Forge that CMDCam depends on CreativeCore. When CreativeCore is absent, now Forge should show this window instead of simple crashing Minecraft without any messages: 
Absent core mod

**Comment by whitebear60** [comment]
I haven't made CMDCam independent of CreativeCore, no.

**Comment by CreativeMD** [comment]
For real? Oh damn, guess I will change it for all my mods then.

**Comment by whitebear60** [comment]
I have learned about this just recently, and, you can see examples of using multiple dependencies in Astral Sorcery repository, for example. If you need this.

**Comment by CreativeMD** [comment]
I knew about the dependency thingy, but it never prevented the crash before CMDCam crashed before the screen appeared (because it has a core mod which requires CreativeCore).

**Comment by whitebear60** [comment]
Check the mod start without dependencies before publishing mods in the future))

**Comment by whitebear60** [comment]
This bugfix should be released on Curseforge as quick as possible))

**Comment by CreativeMD** [comment]
I'm sorry, but I can't at the moment. I will release a wave of fixes and ports once I have done my exams. So at around the beginning of august.

**Pull request merged**
